---

- name: Ensure RPM GPG key is present
  rpm_key:
    key: https://www.virtualbox.org/download/oracle_vbox.asc
    state: present

- name: Ensure Fedora is detected as a Red Hat variant
  set_fact:
    virtualbox_redhat_variant: "fedora"
  when: ansible_distribution | lower == "fedora"

- name: Ensure YUM repository file exists
  yum_repository:
    name: virtualbox
    description: VirtualBox Repository
    file: virtualbox
    baseurl: http://download.virtualbox.org/virtualbox/rpm/{{ virtualbox_redhat_variant }}/$releasever/$basearch
    state: present
    enabled: true
    gpgcheck: true
    gpgkey: https://www.virtualbox.org/download/oracle_vbox.asc

- name: Ensure VirtualBox is installed (YUM)
  yum:
    name: "VirtualBox-{{ virtualbox_version }}"
    state: present
    update_cache: true
  when: ansible_pkg_mgr == "yum"

- name: Ensure VirtualBox is installed (DNF)
  yum:
    name: "VirtualBox-{{ virtualbox_version }}"
    state: present
    update_cache: true
  when: ansible_pkg_mgr == "dnf"
